Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  config.vm.hostname = "it-reverso-nginx-prd-01"
  config.vm.network "public_network", ip: "192.168.0.23", hostname: true
  config.vm.disk :disk, name: "it-reverso-nginx-prd-01", size: "40GB", primary: "true"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "vmware_workstation" do |vmware|
   vmware.gui = true
   vmware.memory = 1024
   vmware.cpus = 1
 end
   config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get upgrade
     apt-get -y install nginx
     apt-get -y install certbot python3-certbot-nginx
   SHELL
end
