Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
   config.vm.network "public_network"
   config.vm.provider "vmware_workstation" do |vmware|
     vmware.gui = true
     vmware.memory = 1024
     vmware.cpus = 1
   end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
