---
- name: Instalando Zabbix nas vms
  hosts: mysql8
  
  tasks:
    - name: Instalar o epel-release
      yum:
        name: epel-release
        state: present

    - name: Atualizar todos os pacotes
      yum:
        name: '*'
        state: latest

    - name: Adicionar a exclusão do zabbix ao arquivo oracle-epel-ol9.repo
      lineinfile:
        path: /etc/yum.repos.d/oracle-epel-ol9.repo
        line: "excludepkgs=zabbix*"

    - name: Adicionar o repositório Zabbix 6.4
      rpm_key:
        state: present
        key: https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-1.el9.noarch.rpm

    - name: Limpar o cache do yum
      command: yum clean all

    - name: Instalar o zabbix-agent2
      yum:
        name: zabbix-agent2
        state: present

    - name: Adicionar a porta 10050 ao firewall
      firewalld:
        port: 10050/tcp
        permanent: yes
        state: enabled

    - name: Recarregar o firewall
      firewalld:
        state: reloaded

    - name: Configurar o arquivo zabbix_agent2.conf
      blockinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        block: |
          Server=172.16.102.12
          ListenPort=10050

    - name: Reiniciar o zabbix-agent2
      service:
        name: zabbix-agent2
        state: restarted
#    - name: Habilitar o zabbix-agent2 no boot
#      service:
#        name: zabbix-agent2
#        enabled: yes
